version: '3'
services:
  api:
    build: .
    ports:
      - '5000:5000'
    links:
      - mysql
    volumes:
      - '.:/go/src/github.com/m-nakamura145/golang-docker-compose-sample'
    depends_on:
      - mysql
    command: go run cmd/main.go
  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
